raster_plot(lonlat_raster$count, png_file = "out/maps/lonlat_raster-count.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w1a, png_file = "out/maps/lonlat_raster-w1a.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w1b, png_file = "out/maps/lonlat_raster-w1b.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w2a, png_file = "out/maps/lonlat_raster-w2a.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w2b, png_file = "out/maps/lonlat_raster-w2b.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w3, png_file = "out/maps/lonlat_raster-w3.png", bg_color = "#440154FF")
raster_plot(lonlat_raster$w4, png_file = "out/maps/lonlat_raster-w4.png", bg_color = "#440154FF")

raster_plot(hires_raster$count, png_file = "out/maps/hires_raster-count.png", bg_color = "#440154FF")
raster_plot(hires_raster$w1a, png_file = "out/maps/hires_raster-w1a.png", bg_color = "#440154FF")
raster_plot(hires_raster$w1b, png_file = "out/maps/hires_raster-w1b.png", bg_color = "#440154FF")
raster_plot(hires_raster$w2a, png_file = "out/maps/hires_raster-w2a.png", bg_color = "#440154FF")
raster_plot(hires_raster$w2b, png_file = "out/maps/hires_raster-w2b.png", bg_color = "#440154FF")
raster_plot(hires_raster$w3, png_file = "out/maps/hires_raster-w3.png", bg_color = "#440154FF")
raster_plot(hires_raster$w4, png_file = "out/maps/hires_raster-w4.png", bg_color = "#440154FF")

raster_plot(quantvar(lonlat_raster$count), png_file = "out/maps/quantvar-lonlat_raster-count.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w1a), png_file = "out/maps/quantvar-lonlat_raster-w1a.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w1b), png_file = "out/maps/quantvar-lonlat_raster-w1b.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w2a), png_file = "out/maps/quantvar-lonlat_raster-w2a.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w2b), png_file = "out/maps/quantvar-lonlat_raster-w2b.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w3), png_file = "out/maps/quantvar-lonlat_raster-w3.png", bg_color = "#440154FF")
raster_plot(quantvar(lonlat_raster$w4), png_file = "out/maps/quantvar-lonlat_raster-w4.png", bg_color = "#440154FF")

raster_plot(quantvar(hires_raster$count), png_file = "out/maps/quantvar-hires_raster-count.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w1a), png_file = "out/maps/quantvar-hires_raster-w1a.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w1b), png_file = "out/maps/quantvar-hires_raster-w1b.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w2a), png_file = "out/maps/quantvar-hires_raster-w2a.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w2b), png_file = "out/maps/quantvar-hires_raster-w2b.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w3), png_file = "out/maps/quantvar-hires_raster-w3.png", bg_color = "#440154FF")
raster_plot(quantvar(hires_raster$w4), png_file = "out/maps/quantvar-hires_raster-w4.png", bg_color = "#440154FF")

raster_plot(winsorize(lonlat_raster$count), png_file = "out/maps/winsorize-lonlat_raster-count.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w1a), png_file = "out/maps/winsorize-lonlat_raster-w1a.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w1b), png_file = "out/maps/winsorize-lonlat_raster-w1b.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w2a), png_file = "out/maps/winsorize-lonlat_raster-w2a.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w2b), png_file = "out/maps/winsorize-lonlat_raster-w2b.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w3), png_file = "out/maps/winsorize-lonlat_raster-w3.png", bg_color = "#440154FF")
raster_plot(winsorize(lonlat_raster$w4), png_file = "out/maps/winsorize-lonlat_raster-w4.png", bg_color = "#440154FF")

raster_plot(winsorize(hires_raster$count), png_file = "out/maps/winsorize-hires_raster-count.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w1a), png_file = "out/maps/winsorize-hires_raster-w1a.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w1b), png_file = "out/maps/winsorize-hires_raster-w1b.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w2a), png_file = "out/maps/winsorize-hires_raster-w2a.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w2b), png_file = "out/maps/winsorize-hires_raster-w2b.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w3), png_file = "out/maps/winsorize-hires_raster-w3.png", bg_color = "#440154FF")
raster_plot(winsorize(hires_raster$w4), png_file = "out/maps/winsorize-hires_raster-w4.png", bg_color = "#440154FF")